name: smart_gallery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.1
  http: ^0.13.5
  hive: ^2.1.0
  sizer: ^2.0.15
  image: ^3.2.0
  lottie: ^1.3.0
  sqflite: ^2.0.3
  provider: ^6.0.2
  photo_view: ^0.14.0
  photo_gallery: ^1.1.1
  path_provider: ^2.0.10
  system_settings: ^2.1.0
  achievement_view: ^1.0.0
  easy_localization: ^3.0.0
  salomon_bottom_bar: ^3.3.1
  permission_handler: ^10.2.0
  introduction_screen: ^3.0.1
  flutter_native_splash: ^2.2.7
  flutter_foreground_task: ^3.10.0
  image_vision: ^1.0.0
  hive_flutter: any
  share_plus: ^6.3.0
  chips_choice_null_safety: ^2.0.6
  flutter_photo_editor: ^0.0.3
  dropbox_client: ^1.0.0
  sn_progress_dialog: ^1.0.9
  open_file_plus: ^3.3.0
  workmanager: ^0.5.1
  device_info_plus: ^8.0.0
  exif: ^3.1.2
  google_maps_flutter: ^2.2.1
  connectivity_plus: ^3.0.2
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  file_cryptor: ^0.0.3
  url_launcher: ^6.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/png/
    - assets/images/jpeg/
    - assets/images/gif/
    - assets/animations/json/

  fonts:
    - family: productSansItalic
      fonts:
        - asset: assets/fonts/productSans/ProductSansRegular.ttf
        - asset: assets/fonts/productSans/ProductSansItalic.ttf
          style: italic

    - family: productSansBold
      fonts:
        - asset: assets/fonts/productSans/ProductSansRegular.ttf
        - asset: assets/fonts/productSans/ProductSansBold.ttf
          weight: 700

    - family: productSans
      fonts:
        - asset: assets/fonts/productSans/ProductSansRegular.ttf